spring.application.name=bank-management-system

spring.datasource.url=jdbc:postgresql://localhost:5432/bank_management_db
spring.datasource.username=postgres
spring.datasource.password=Admin@123

#Ye hibernate ko bolti hai ki Java entities ke according database schema ko create/update karo.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false